# - name: Update system
#   apt:
#     update_cache: yes
#     upgrade: dist

# - name: Install base packages
#   apt:
#     name:
#       - curl
#       - wget
#     state: present


- name: Update system
  yum:
    name: "*"
    state: latest
    update_cache: yes

- name: Install base packages
  yum:
    name:
      - curl
      - wget
    state: present
